In [1]:
pip install pandas sklearn tensorflow


  Using cached https://files.pythonhosted.org/packages/1e/7a/dbb3be0ce9bd5c8b7e3d87328e79063f8b263b2b1bfa4774cb1147bfcd3f/sklearn-0.0.tar.gz
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1321 sha256=c8940650235ca6fb2fcf8e98b706de9b237e3503e3ebbeb118989461d4c7af65
  Stored in directory: C:\Users\RISHABH\AppData\Local\pip\Cache\wheels\76\03\bb\589d421d27431bcd2c6da284d5f2286c8e3b2ea3cf1594c074
Successfully built sklearn
Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Tdata.csv')

In [4]:
df.head

<bound method NDFrame.head of       Fever  Age  Bpain  Cough  Breathing  ChestPain  TestResult
0        98   57      1      0          1          1           1
1        98   88      0      1          0          0           0
2        99   53      1      1          1          1           1
3       101   50      0      1          0          0           0
4        98   91      1      1          1          0           1
...     ...  ...    ...    ...        ...        ...         ...
2313     99   23      1      0          0          1           1
2314    103   59      1      0          0          0           0
2315    102   69      0      1          0          1           0
2316     99   42      0      1          1          0           0
2317    103   98      0      1          1          0           0

[2318 rows x 7 columns]>

In [5]:
df.head()

Fever  Age  Bpain  Cough  Breathing  ChestPain  TestResult
0     98   57      1      0          1          1           1
1     98   88      0      1          0          0           0
2     99   53      1      1          1          1           1
3    101   50      0      1          0          0           0
4     98   91      1      1          1          0           1

In [6]:
df.tail()

Fever  Age  Bpain  Cough  Breathing  ChestPain  TestResult
2313     99   23      1      0          0          1           1
2314    103   59      1      0          0          0           0
2315    102   69      0      1          0          1           0
2316     99   42      0      1          1          0           0
2317    103   98      0      1          1          0           0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2318 entries, 0 to 2317
Data columns (total 7 columns):
Fever         2318 non-null int64
Age           2318 non-null int64
Bpain         2318 non-null int64
Cough         2318 non-null int64
Breathing     2318 non-null int64
ChestPain     2318 non-null int64
TestResult    2318 non-null int64
dtypes: int64(7)
memory usage: 126.9 KB


In [8]:
df['Fever'].value_counts()

101    348
104    341
103    331
99     330
100    328
98     324
102    316
Name: Fever, dtype: int64

In [9]:
df.describe()

Fever          Age        Bpain        Cough    Breathing  \
count  2318.000000  2318.000000  2318.000000  2318.000000  2318.000000   
mean    101.017688    54.757981     0.489215     0.486195     0.483175   
std       2.000461    32.235640     0.499992     0.499917     0.499825   
min      98.000000     0.000000     0.000000     0.000000     0.000000   
25%      99.000000    27.000000     0.000000     0.000000     0.000000   
50%     101.000000    55.000000     0.000000     0.000000     0.000000   
75%     103.000000    83.000000     1.000000     1.000000     1.000000   
max     104.000000   110.000000     1.000000     1.000000     1.000000   

         ChestPain   TestResult  
count  2318.000000  2318.000000  
mean      0.515531     0.516393  
std       0.499867     0.499839  
min       0.000000     0.000000  
25%       0.000000     0.000000  
50%       1.000000     1.000000  
75%       1.000000     1.000000  
max       1.000000     1.000000

In [10]:
import numpy as np

#Train-Test Split

In [12]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data)*ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]

In [14]:
train,test = data_split(df,0.2)

In [15]:
train

Fever  Age  Bpain  Cough  Breathing  ChestPain  TestResult
1452     99   45      0      1          0          1           0
1989    104   19      1      0          1          0           1
1827     99  105      0      1          0          1           0
2108    104   89      1      1          1          0           1
1173     98   39      1      0          0          1           0
...     ...  ...    ...    ...        ...        ...         ...
1638    103  105      1      0          0          1           1
1095    102   40      0      0          0          0           0
1130    101   43      0      1          1          0           1
1294    102   36      1      1          1          1           1
860     100   26      0      1          0          0           1

[1855 rows x 7 columns]

In [16]:
test

Fever  Age  Bpain  Cough  Breathing  ChestPain  TestResult
1040    104   37      0      0          1          1           1
548      99   91      0      1          0          0           1
100     104  109      0      1          0          0           0
1044    103   49      1      0          1          1           1
251      98   62      0      1          1          1           1
...     ...  ...    ...    ...        ...        ...         ...
907     102   55      0      1          1          1           1
707     100   55      1      0          1          1           0
2216     98   52      0      1          0          0           1
1491     98   25      1      1          0          0           0
1523    104   11      0      1          0          1           0

[463 rows x 7 columns]

In [27]:
x_train = train[['Fever','Age','Bpain','Cough','Breathing','ChestPain']].to_numpy()

In [18]:
x_train

array([[ 99,  45,   0,   1,   0,   1],
       [104,  19,   1,   0,   1,   0],
       [ 99, 105,   0,   1,   0,   1],
       ...,
       [101,  43,   0,   1,   1,   0],
       [102,  36,   1,   1,   1,   1],
       [100,  26,   0,   1,   0,   0]], dtype=int64)

In [28]:
x_test = test[['Fever','Age','Bpain','Cough','Breathing','ChestPain']].to_numpy()

In [20]:
x_test

array([[104,  37,   0,   0,   1,   1],
       [ 99,  91,   0,   1,   0,   0],
       [104, 109,   0,   1,   0,   0],
       ...,
       [ 98,  52,   0,   1,   0,   0],
       [ 98,  25,   1,   1,   0,   0],
       [104,  11,   0,   1,   0,   1]], dtype=int64)

In [29]:
y_train = train[['TestResult']].to_numpy().reshape(1855,)

In [30]:
y_train

array([0, 1, 0, ..., 1, 1, 1], dtype=int64)

In [31]:
y_test = test[['TestResult']].to_numpy().reshape(463,)

In [32]:
y_test

array([1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,

# we are using logistic regression to model this

In [33]:
from sklearn.linear_model import LogisticRegression 

In [34]:
clf = LogisticRegression()
clf.fit(x_train,y_train)

C:\Users\RISHABH\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [43]:
inputFeatures = [100,77,0,0,0,0]
infProb = clf.predict_proba([inputFeatures])[0][1]

In [44]:
infProb

0.5267722746752236